// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StrategyForge.Infrastructure.Data;

#nullable disable

namespace StrategyForge.Infrastructure.Migrations
{
    [DbContext(typeof(StrategyForgeDbContext))]
    [Migration("20260924050042_InitialDatasets")]
    partial class InitialDatasets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StrategyForge.Infrastructure.Data.Entities.EnrichedObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Change")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ChangePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<string>("IndicatorsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ObservationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<string>("WarningCodesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ObservationDate");

                    b.HasIndex("InstrumentId", "Source", "ObservationDate")
                        .IsUnique()
                        .HasDatabaseName("IX_EnrichedObservations_Identity");

                    b.ToTable("EnrichedObservations");
                });

            modelBuilder.Entity("StrategyForge.Infrastructure.Data.Entities.EvidenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssembledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssetJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetMarket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("DataQualityScore")
                        .HasColumnType("numeric");

                    b.Property<string>("DataSources")
                        .HasColumnType("text");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IndicatorCount")
                        .HasColumnType("integer");

                    b.Property<int>("NewsItemCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssembledAt");

                    b.HasIndex("AssetSymbol");

                    b.HasIndex("AssetSymbol", "AssembledAt");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("StrategyForge.Infrastructure.Data.Entities.HistoricalDatasetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdjustmentSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AdjustmentType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("Change")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ChangePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ExtraPropertiesJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<string>("MarketTimezone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("ObservationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SourceCalendar")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceDate")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceInstrumentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceSymbol")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("TradeCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ObservationDate");

                    b.HasIndex("InstrumentId", "Source", "ObservationDate")
                        .IsUnique()
                        .HasDatabaseName("IX_HistoricalDataset_Identity");

                    b.ToTable("HistoricalDataset");
                });

            modelBuilder.Entity("StrategyForge.Infrastructure.Data.Entities.IntelligenceRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EvidenceIdsJson")
                        .HasColumnType("text");

                    b.Property<int>("FailedAssets")
                        .HasColumnType("integer");

                    b.Property<bool>("GenerateStrategies")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StrategyIdsJson")
                        .HasColumnType("text");

                    b.Property<int>("SuccessfulAssets")
                        .HasColumnType("integer");

                    b.Property<string>("TargetAssetsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalTokensUsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("State");

                    b.ToTable("IntelligenceRuns");
                });

            modelBuilder.Entity("StrategyForge.Infrastructure.Data.Entities.StrategyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetMarket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContributingAgents")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("GenerationDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("LlmModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("OverallConfidence")
                        .HasColumnType("numeric");

                    b.Property<string>("OverallSentiment")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PipelineState")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetSymbol");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("AssetSymbol", "GeneratedAt");

                    b.ToTable("Strategies");
                });
#pragma warning restore 612, 618
        }
    }
}
